import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const iosRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(iosRoot, '..', '..');
const themePath = path.join(repoRoot, 'shared', 'brand', 'theme.ts');
const tokensPath = path.join(repoRoot, 'shared', 'brand', 'tokens.css');
const outputPath = path.join(iosRoot, 'src', 'generated', 'brandTokens.ts');

function stripComments(value) {
  return value.replace(/\/\*[\s\S]*?\*\//g, '');
}

function extractBlock(source, selector) {
  const start = source.indexOf(selector);
  if (start === -1) {
    throw new Error(`Unable to find selector: ${selector}`);
  }

  const openIndex = source.indexOf('{', start);
  if (openIndex === -1) {
    throw new Error(`Unable to find opening brace for selector: ${selector}`);
  }

  let depth = 0;
  for (let index = openIndex; index < source.length; index += 1) {
    if (source[index] === '{') depth += 1;
    if (source[index] === '}') depth -= 1;
    if (depth === 0) {
      return source.slice(openIndex + 1, index);
    }
  }

  throw new Error(`Unable to find closing brace for selector: ${selector}`);
}

function parseVariables(block) {
  const variables = {};
  const matcher = /--([a-z0-9-]+)\s*:\s*([\s\S]*?);/gi;

  for (const match of block.matchAll(matcher)) {
    const [, name, rawValue] = match;
    variables[name] = rawValue.replace(/\s+/g, ' ').trim();
  }

  return variables;
}

function parseThemes(source) {
  const matcher =
    /name:\s*"([^"]+)"[\s\S]*?label:\s*"([^"]+)"[\s\S]*?description:\s*"([^"]+)"[\s\S]*?}/g;
  const themes = [];

  for (const match of source.matchAll(matcher)) {
    const [, name, label, description] = match;
    themes.push({ name, label, description });
  }

  if (!themes.length) {
    throw new Error('Unable to parse theme metadata from shared/brand/theme.ts');
  }

  const defaultMatch = source.match(/DEFAULT_THEME:\s*ThemeName\s*=\s*"([^"]+)"/);
  if (!defaultMatch) {
    throw new Error('Unable to parse DEFAULT_THEME from shared/brand/theme.ts');
  }

  return { themes, defaultTheme: defaultMatch[1] };
}

const themeSource = fs.readFileSync(themePath, 'utf8');
const cssSource = stripComments(fs.readFileSync(tokensPath, 'utf8'));
const { themes, defaultTheme } = parseThemes(themeSource);

const tokensByTheme = {
  light: parseVariables(extractBlock(cssSource, ':root,')),
  dark: parseVariables(extractBlock(cssSource, '[data-theme="dark"]')),
  paper: parseVariables(extractBlock(cssSource, '[data-theme="paper"]')),
};

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(
  outputPath,
  `/* eslint-disable */
// This file is generated by scripts/sync-brand.mjs.
// Edit shared/brand/* and rerun the sync script instead of changing this file by hand.

export const BRAND_THEME_ORDER = ${JSON.stringify(themes.map((theme) => theme.name), null, 2)} as const;
export type BrandThemeName = (typeof BRAND_THEME_ORDER)[number];
export const DEFAULT_THEME_NAME = ${JSON.stringify(defaultTheme)} as BrandThemeName;

export const BRAND_THEMES = ${JSON.stringify(
    themes.reduce((accumulator, theme) => {
      accumulator[theme.name] = {
        label: theme.label,
        description: theme.description,
        tokens: tokensByTheme[theme.name],
      };
      return accumulator;
    }, {}),
    null,
    2,
  )} as const;
`,
);

console.log(`Synced brand tokens from shared/brand into ${path.relative(iosRoot, outputPath)}`);
